name = "chickenroad-game-app-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroad-game-app.com"
HMAC_KEY = "c3e31ac09690f4e9d085816a9c7a666e1b6ec4d3aa5486452c1b738cd30659ad"
COOKIE_NAME = "38s"
PLAY_PATH = "start"
BUTTON_ID = "p68041e91117243704e1c1d5e5c236cbe"
GATE_SALT = "b25a15a0e769fbf5"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0s0v"
CTA_SELECTOR = ".play-button"
